# Base image node to install Vue dependencies
FROM node:14.13.1 AS build-stage

WORKDIR /app

# Install dependencies in separate step to cache
COPY package.json ./
RUN yarn install --frozen-lockfile

# Build dependencies into dist folder, copy line may change as we restructure
COPY . .
ENTRYPOINT yarn serve