version: "3"
services:
  production:
    image: production
    build: .
    restart: always
    ports: 
      - '1323:1323'
    security_opt:
      - no-new-privileges
    read_only: true
    depends_on:
      - mongo
    container_name: production
  mongo:
    image: mongo:3.6.20-xenial
    restart: always
    ports:
      - '27017:27017'
    security_opt:
      - no-new-privileges
    read-only: true
    container_name: mongo
    