# Docker compose development version 
version: "3"
services:
    frontend:
        image: frontend
        build: 
            context: ./frontend
            dockerfile: Dockerfile-dev
        ports:
            - '8080:8080'
        container_name: frontend
        volumes:
            - /app/node_modules
            - ./frontend:/app
        environment: 
            - CHOKIDAR_USEPOLLING=true
    backend:
        image: backend
        build: ./backend
        ports:
            - '1323:1323'
        volumes:
            - ./backend:/app/server
        container_name: backend
        environment: 
            - MAILJET_TOKEN=${MAILJET_TOKEN}
            - FB_TOKEN=${FB_TOKEN}
            - JWT_SECRET=${JWT_SECRET}
            - TESTING_JWT=${TESTING_JWT}
    mongo:
        image: mongo:latest
        restart: always
        ports:
            - '27017:27017'
        container_name: mongo