// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Tommy Truong",
            "email": "projects.website@csesoc.org.au"
        },
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/sponsors": {
            "get": {
                "tags": [
                    "sponsors"
                ],
                "summary": "Get a list of sponsors stored",
                "parameters": [
                    {
                        "maximum": 2,
                        "minimum": 0,
                        "type": "integer",
                        "description": "Valid sponsor tier",
                        "name": "name",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main.Sponsor"
                            }
                        }
                    },
                    "500": {
                        "description": "Error acessing the database"
                    }
                }
            },
            "post": {
                "tags": [
                    "sponsors"
                ],
                "summary": "Add a new sponsor",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Name",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Logo URL",
                        "name": "logo",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "maximum": 2,
                        "minimum": 0,
                        "type": "integer",
                        "description": "Valid tier",
                        "name": "tier",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Detail",
                        "name": "detail",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Sponsor added"
                    },
                    "400": {
                        "description": "Error acessing the database"
                    },
                    "409": {
                        "description": "Sponsor already exists on database"
                    }
                }
            }
        },
        "/sponsors/{name}": {
            "get": {
                "tags": [
                    "sponsors"
                ],
                "summary": "Find entry for a specific sponsor",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sponsor name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.Sponsor"
                        }
                    },
                    "404": {
                        "description": "No such sponsor"
                    }
                }
            },
            "delete": {
                "tags": [
                    "sponsors"
                ],
                "summary": "Delete a sponsor",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sponsor name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Sponsor deleted"
                    },
                    "500": {
                        "description": "Error acessing the database"
                    }
                }
            }
        }
    },
    "definitions": {
        "main.Sponsor": {
            "type": "object",
            "required": [
                "detail",
                "logo",
                "name",
                "tier"
            ],
            "properties": {
                "detail": {
                    "type": "string"
                },
                "logo": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "tier": {
                    "type": "integer"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "",
	BasePath:    "/api/v1",
	Schemes:     []string{},
	Title:       "CSESoc Website Swagger API",
	Description: "Swagger API for the CSESoc Website Project.",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
