# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Building docker containers using docker-compose
        env:
          MAILJET_TOKEN: ${{ secrets.MAILJET_TOKEN }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: docker-compose up -d --build backend mongo
      - name: Golang Tests
        run: go test ./...
        working-directory: ./backend/server
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: yarn
        working-directory: ./frontend
      - name: Cypress Tests
        uses: cypress-io/github-action@v1
        with:
          start: yarn serve
          wait-on: http://localhost:8080 
          working-directory: ./frontend